"""Deterministic, disposable Markdown navigation views.

Canonical Markdown stays the only authority. These pages are a project-owned
projection of it: Tangle regenerates them from the same canonical snapshot
its index reconciles, and a client never edits or maintains one by hand. They
carry no authoritative field, no generation timestamp, and no volatile data, so
an unchanged vault reproduces them byte for byte and a no-op interaction
rewrites nothing.

Every page groups or orders nodes by a value already stored on the node and
renders the canonical summary as the link display text. The link target is the
node's full stable basename, so a page keeps working after a status change and
never depends on a status directory or a client-maintained alias.
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass
from typing import TYPE_CHECKING

from . import identity

if TYPE_CHECKING:
    from .index import IndexedNode

__all__ = [
    "GENERATED_NOTICE",
    "PROJECT_REGISTRY_FILE",
    "VIEW_DIRECTORY",
    "ViewReport",
    "build",
    "inspect_report",
    "publish",
]

VIEW_DIRECTORY = "views"
PROJECT_REGISTRY_FILE = "projects.json"

# Fixed presentation orders keep grouping deterministic: the same canonical
# snapshot always produces the same headings in the same sequence.
_STATUS_ORDER = ("active", "proposed", "blocked", "resolved")
_PRIORITY_ORDER = ("P0", "P1", "P2", "P3")
_RECENT_LIMIT = 50

GENERATED_NOTICE = (
    "<!-- Generated by tangle from canonical nodes. Do not edit; "
    "this page is regenerated and never authoritative. -->"
)


@dataclass(frozen=True)
class ViewReport:
    """The pages one publication pass wrote, left alone, or removed."""

    written: tuple[str, ...]
    unchanged: tuple[str, ...]
    removed: tuple[str, ...]

    @property
    def updated(self) -> int:
        """Return the number of pages this pass created, changed, or removed."""
        return len(self.written) + len(self.removed)

    @property
    def current(self) -> bool:
        """Return whether every generated page already matched the vault."""
        return self.updated == 0


def _display(summary: str) -> str:
    """Return a wikilink display text that cannot break the surrounding link."""
    text = " ".join(summary.split())
    for removed in ("|", "[", "]"):
        text = text.replace(removed, " ")
    return " ".join(text.split())


def _link(node: IndexedNode) -> str:
    """Return one node as a summary-rendering wikilink to its stable basename."""
    summary = _display(node.metadata.get("summary", ""))
    if not summary:
        return f"[[{node.name}]]"
    return f"[[{node.name}|{summary}]]"


def _render(title: str, groups: list[tuple[str, list[IndexedNode]]]) -> str:
    """Render one deterministic page from its ordered heading groups."""
    lines = [GENERATED_NOTICE, "", f"# {title}", ""]
    if not groups:
        lines.extend(["_No nodes._", ""])
    for heading, members in groups:
        lines.extend([f"## {heading}", ""])
        lines.extend(f"- {_link(node)}" for node in members)
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def _by_status(nodes: list[IndexedNode]) -> str:
    groups: list[tuple[str, list[IndexedNode]]] = []
    for status in _STATUS_ORDER:
        members = sorted(
            (node for node in nodes if node.status == status),
            key=lambda node: node.id,
        )
        if members:
            groups.append((f"{status} ({len(members)})", members))
    return _render("By status", groups)


def _primary_area(node: IndexedNode) -> str:
    """Return the node's ``Area`` target name, else its ``Parent`` target name.

    The primary link is the one durable route the node stores. An area link is
    the stronger grouping signal, so it wins when a node carries both.
    """
    from .index import _PRIMARY_ROUTE  # local import avoids an import cycle

    area = parent = ""
    for relation, target in _PRIMARY_ROUTE.findall(node.body):
        if relation == "Area":
            area = area or target
        elif relation == "Parent":
            parent = parent or target
    return area or parent


def _by_area(nodes: list[IndexedNode]) -> str:
    grouped: dict[str, list[IndexedNode]] = {}
    for node in nodes:
        grouped.setdefault(_primary_area(node), []).append(node)
    groups = [
        (
            target if target else "Unassigned",
            sorted(grouped[target], key=lambda node: node.id),
        )
        for target in sorted(grouped)
    ]
    return _render("By area", groups)


def _by_priority(nodes: list[IndexedNode]) -> str:
    groups: list[tuple[str, list[IndexedNode]]] = []
    for priority in _PRIORITY_ORDER:
        members = sorted(
            (node for node in nodes if node.metadata.get("priority") == priority),
            key=lambda node: node.id,
        )
        if members:
            groups.append((f"{priority} ({len(members)})", members))
    unprioritised = sorted(
        (node for node in nodes if node.metadata.get("priority", "") not in _PRIORITY_ORDER),
        key=lambda node: node.id,
    )
    if unprioritised:
        groups.append((f"no priority ({len(unprioritised)})", unprioritised))
    return _render("By priority", groups)


def _recent(nodes: list[IndexedNode]) -> str:
    ordered = sorted(
        nodes,
        key=lambda node: (node.metadata.get("updated", ""), node.id),
        reverse=True,
    )[:_RECENT_LIMIT]
    if not ordered:
        return _render("Recent", [])
    return _render("Recent", [("Most recently updated", ordered)])


def _registered_projects(root: str) -> list[tuple[str, str, bool]]:
    """Return ``(alias, uid, present)`` for each project in the local registry.

    The registry maps a lowercase alias to an immutable project UID and a local
    vault location. It is local state, not canonical Markdown, so a missing or
    malformed file simply yields no registrations rather than failing a command.
    """
    path = os.path.join(root, PROJECT_REGISTRY_FILE)
    try:
        with open(path, encoding="utf-8") as handle:
            document = json.load(handle)
    except (OSError, ValueError):
        return []
    if not isinstance(document, dict):
        return []
    projects = document.get("projects", document)
    if not isinstance(projects, dict):
        return []
    entries: list[tuple[str, str, bool]] = []
    for alias, value in projects.items():
        if not isinstance(value, dict):
            continue
        uid = value.get("uid", "")
        location = value.get("path", "")
        present = bool(location) and os.path.isdir(
            location if os.path.isabs(location) else os.path.join(root, location)
        )
        entries.append((str(alias), str(uid), present))
    entries.sort(key=lambda entry: entry[0])
    return entries


def _projects(root: str) -> str:
    lines = [GENERATED_NOTICE, "", "# Registered external projects", ""]
    entries = _registered_projects(root)
    if not entries:
        lines.extend(
            [
                "_No registered external projects._",
                "",
                f"Register one in `.tangle/{PROJECT_REGISTRY_FILE}` with a "
                "lowercase alias, its `prj-` UID, and a local path.",
                "",
            ]
        )
        return "\n".join(lines)

    for alias, uid, present in entries:
        valid = identity.is_project_uid(uid)
        lines.extend([f"## {alias}", ""])
        lines.append(f"- project: {uid}" if valid else f"- project: {uid} (not a prj- UID)")
        lines.append(f"- local: {'present' if present else 'unavailable'}")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def build(root: str) -> dict[str, str]:
    """Return the deterministic generated pages for the canonical store at ``root``."""
    from .index import _read_nodes  # local import avoids an import cycle

    nodes = sorted(_read_nodes(root), key=lambda node: node.id)
    return {
        "by-status.md": _by_status(nodes),
        "by-area.md": _by_area(nodes),
        "by-priority.md": _by_priority(nodes),
        "recent.md": _recent(nodes),
        "projects.md": _projects(root),
    }


def _directory(root: str) -> str:
    return os.path.join(root, VIEW_DIRECTORY)


def publish(root: str) -> ViewReport:
    """Rebuild the generated pages under ``root/views`` and report the delta.

    A page whose exact bytes already match is left untouched, so an unchanged
    vault performs no write and editors or Git see no churn. Each changed page
    is written to a same-directory temporary file and atomically renamed into
    place, so a reader never observes a half-written page. A generated page
    whose name is no longer produced is removed; an unrelated file left in the
    directory is not touched.
    """
    pages = build(root)
    directory = _directory(root)
    os.makedirs(directory, exist_ok=True)
    written: list[str] = []
    unchanged: list[str] = []
    for name, content in pages.items():
        target = os.path.join(directory, name)
        try:
            with open(target, encoding="utf-8") as handle:
                existing = handle.read()
        except FileNotFoundError:
            existing = None
        if existing == content:
            unchanged.append(name)
            continue
        # The temporary name carries the process id so two concurrent writers
        # never race on the same staging file; both replace the target with the
        # same canonical bytes, so the last writer still publishes one page.
        temporary = f"{target}.{os.getpid()}.tmp"
        try:
            with open(temporary, "w", encoding="utf-8") as handle:
                handle.write(content)
            os.replace(temporary, target)
        except BaseException:
            try:
                os.remove(temporary)
            except OSError:
                pass
            raise
        written.append(name)
    removed: list[str] = []
    for name in sorted(os.listdir(directory)):
        if name in pages or not name.endswith(".md"):
            continue
        try:
            os.remove(os.path.join(directory, name))
        except FileNotFoundError:
            continue
        removed.append(name)
    return ViewReport(tuple(written), tuple(unchanged), tuple(removed))


def inspect_report(root: str) -> ViewReport:
    """Report the pending delta without writing, for a diagnostic surface."""
    pages = build(root)
    directory = _directory(root)
    written: list[str] = []
    unchanged: list[str] = []
    for name, content in pages.items():
        target = os.path.join(directory, name)
        try:
            with open(target, encoding="utf-8") as handle:
                existing = handle.read()
        except FileNotFoundError:
            existing = None
        if existing == content:
            unchanged.append(name)
        else:
            written.append(name)
    present = set(os.listdir(directory)) if os.path.isdir(directory) else set()
    removed = sorted(
        name for name in present if name.endswith(".md") and name not in pages
    )
    return ViewReport(tuple(written), tuple(unchanged), tuple(removed))
